In [70]:
import numpy as np
import pandas as pd

In [72]:
df_yonalishlar = pd.read_excel('../data/raw/Fanlar_majmuasi_2025-2026.xlsx')
df_abts = pd.read_csv('../data/raw/abt_unique.csv')

In [75]:
df_yonalishlar.head()

,Yoʻnalish kodi,Bakalavriat taʼlim yoʻnalishlari nomi,1-fan,2-fan
0,60110100,Pedagogika,Tarix,Ona tili va adabiyoti
1,60110200,Maktabgacha taʼlim,Biologiya,Ona tili va adabiyoti
2,60110300,Maxsus pedagogika: logopediya,Biologiya,Ona tili va adabiyoti
3,60110300,Maxsus pedagogika: olegofrenopedagogika,Biologiya,Ona tili va adabiyoti
4,60110300,Maxsus pedagogika: surdopedagogika,Biologiya,Ona tili va adabiyoti

In [78]:
df_yonalishlar.info()

<class 'pandas.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 4 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Yoʻnalish kodi                         218 non-null    int64
 1   Bakalavriat taʼlim yoʻnalishlari nomi  218 non-null    str
 2   1-fan                                  218 non-null    str
 3   2-fan                                  218 non-null    str
dtypes: int64(1), str(3)
memory usage: 6.9 KB

In [81]:
df_abts.head()

,ismi,ID,otm_nomi,yonalishi,shifr_kodi,talim_tili,talim_shakli,toplagan_bali
0,URAKBAYEV N. M.,6042695,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,189.0
1,NAZEROV I. A.,6045467,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,189.0
2,TENGELOV X. I.,6872807,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,189.0
3,JANABAYEV S. O.,6259423,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,186.7
4,ERDOSHEVA X. T.,6980903,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,185.7

In [82]:
df_abts.info()

<class 'pandas.DataFrame'>
RangeIndex: 357561 entries, 0 to 357560
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ismi           357561 non-null  str
 1   ID             357561 non-null  int64
 2   otm_nomi       357561 non-null  str
 3   yonalishi      357561 non-null  str
 4   shifr_kodi     357561 non-null  int64
 5   talim_tili     357561 non-null  str
 6   talim_shakli   357559 non-null  str
 7   toplagan_bali  357561 non-null  float64
dtypes: float64(1), int64(2), str(5)
memory usage: 21.8 MB

In [92]:
royxat1 = df_abts['yonalishi'].unique()
royxat2 = df_yonalishlar['Bakalavriat taʼlim yoʻnalishlari nomi'].unique()

# Har ehtimolga qarshi hammasini kichik harfga o'tkazib to'plamga aylantiramiz
set1 = set([str(x).lower().strip() for x in royxat1])
set2 = set([str(x).lower().strip() for x in royxat2])

print("Ikkalasida ham borlari (Kesishmasi):", set1.intersection(set2))
print("Faqat 1-ro'yxatda bor, lekin 2-da yo'qlar:", set1.difference(set2))
print("Faqat 2-ro'yxatda bor, lekin 1-da yo'qlar:", set2.difference(set1))

Ikkalasida ham borlari (Kesishmasi): {'qurilish muhandisligi', 'biologiya', 'astronomiya', 'yer kadastri va yer tuzish', 'oʻzbek tili va adabiyoti', 'ona tili va adabiyoti: qozoq tili', 'xorijiy til va adabiyoti: nemis tili', 'bank ishi', 'veterinariya sanitariya ekspertizasi', 'kompyuter lingvistikasi', 'muzeyshunoslik: muzey menejmenti va madaniy turizm', 'parfyumeriya-kosmetika mahsulotlari texnologiyasi', 'chaqiriqqacha harbiy taʼlim', 'tarjima nazariyasi va amaliyoti: xitoy tili', 'logistika', 'filologiya va tillarni oʻqitish: nemis tili', 'hayot faoliyati xavfsizligi', 'kiberxavfsizlik injiniringi', 'jurnalistika', 'axborot tizimlari va texnologiyalari', 'muzeyshunoslik: muzey predmetlari ekspertizasi, konservatsiyalash va taʼmirlash', 'filologiya va tillarni oʻqitish: qozoq tili', 'tarjima nazariyasi va amaliyoti: nemis tili', 'maxsus pedagogika: tiflopedagogika', 'suv taʼminoti muhandislik tizimlari', 'tasviriy sanʼat va muhandislik grafikasi', 'filologiya va tillarni oʻqitish: dariy tili', 'qishloq xoʻjaligini mexanizatsiyalashtirish', 'gidrogeologiya va muhandislik geologiyasi', 'havodagi harakatni boshqarish', 'texnologik taʼlim', 'dasturiy injiniring', 'tarjima nazariyasi va amaliyoti: arab tili', 'adaptiv jismoniy tarbiya va sport', 'kompyuter injiniringi', 'pediatriya ishi', 'neft va gaz ishi', 'stomatologiya', 'agronomiya', 'shahar qurilishi va loyihalash', 'suv xoʻjaligi va melioratsiya', 'sanoat farmatsiyasi', 'mexanika va matematik modellashtirish', 'jismoniy madaniyat', 'kino-teleoperatorlik', 'qishloq xoʻjaligi ekinlari seleksiyasi va urugʻchiligi', 'filologiya va tillarni oʻqitish: turk tili', 'siyosatshunoslik', 'tarix', 'havo kemalarining parvoz ekspluatatsiyasi', 'davlat va jamiyat boshqaruvi', 'filologiya va tillarni oʻqitish: indonez tili', 'arxivshunoslik', 'yoʻl harakatini tashkil etish', 'inson resurslarini boshqarish', 'farmatsiya', 'konchilik elektr mexanikasi', 'xorijiy til va adabiyoti: ingliz tili', 'milliy gʻoya, maʼnaviyat asoslari va huquq taʼlimi', 'metrologiya va standartlashtirish', 'filologiya va tillarni oʻqitish: yapon tili', 'geodeziya va geoinformatika', 'axborot xizmati va jamoatchilik bilan aloqalar', 'atrof-muhit muhandisligi', 'ijtimoiy ish', 'aviatsiya muhandisligi', 'dinshunoslik', 'kimyo muhandisligi', 'filologiya va tillarni oʻqitish: koreys tili', 'fundamental tibbiyot', 'ona tili va adabiyoti: qoraqalpoq tili', 'falsafa', 'transport vositalari muhandisligi', 'filologiya va tillarni oʻqitish: fransuz tili', 'sunʼiy intellekt', 'fizika', 'maxsus pedagogika: logopediya', 'maxsus pedagogika: surdotarjimonlik faoliyati', 'filologiya va tillarni oʻqitish: tojik tili', 'matematika', 'noyob va radioaktiv metallar rudalarini qazib olish, qayta ishlash texnikasi va texnologiyasi', 'ekologiya va atrof-muhit muhofazasi', 'suv bioresurslari va akvakultura', 'geologiya', 'kimyo', 'gidroenergetika', 'meteorologiya va iqlimshunoslik', 'tibbiy profilaktika ishi', 'filologiya va tillarni oʻqitish: ispan tili', 'moliya va moliyaviy texnologiyalar', 'antropologiya va etnologiya', 'gazni chuqur qayta ishlash texnologiyasi', 'jahon iqtisodiyoti va xalqaro iqtisodiy munosabatlar', 'oliy hamshiralik ishi', 'biotibbiyot muhandisligi', 'pedagogika', 'pochta aloqasi texnologiyasi', 'noshirlik ishi', 'materialshunoslik', 'axborot xavfsizligi', 'gidrologiya', 'yoʻl muhandisligi', 'filologiya va tillarni oʻqitish: oʻzbek tili', 'menejment', 'madaniyatshunoslik', 'metallar texnologiyalari', 'arxitektura yodgorliklari rekonstruksiyasi va restavratsiyasi', 'oʻsimliklar himoyasi va karantini', 'radioelektron qurilmalar va tizimlar', 'islomshunoslik', 'maktabgacha taʼlim', 'mehnat muhofazasi va texnika xavfsizligi', 'maxsus pedagogika: olegofrenopedagogika', 'tarjima nazariyasi va amaliyoti: koreys tili', 'biotexnologiya', 'yurisprudensiya', 'konchilik ishi', 'qiymat injiniringi va koʻchmas mulkni boshqarish', 'xalqaro munosabatlar', 'amaliy matematika', 'texnologik jarayonlar va ishlab chiqarishni avtomatlashtirish', 'mexanika muhandisligi', 'filologiya va tillarni oʻqitish: qoraqalpoq tili', 'gidrotexnika va geotexnika muhandisligi', 'mexatronika va robototexnika', 'elektronika va asbobsozlik', 'meva-sabzavotchilik va uzumchilik', 'filologiya va tillarni oʻqitish: turkman tili', 'filologiya va tillarni oʻqitish: italyan tili', 'meliorativ gidrogeologiya', 'xorijiy til va adabiyoti: fransuz tili', 'qishloq xoʻjalik mahsulotlarini saqlash va qayta ishlash texnologiyasi', 'musiqa taʼlimi', 'filologiya va tillarni oʻqitish: xitoy tili', 'filologiya va tillarni oʻqitish: arab tili', 'buxgalteriya hisobi', 'savdo ishi', 'xorijiy til va adabiyoti: koreys tili', 'maxsus pedagogika: surdopedagogika', 'boshlangʻich taʼlim', 'davolash ishi', 'televizion texnologiyalar', 'energetika muhandisligi', 'geologiya-qidiruv ishlari texnikasi va texnologiyasi', 'tarjima nazariyasi va amaliyoti: ingliz tili', 'kommunal infratuzilmani tashkil etish va boshqarish', 'kadastr', 'telekommunikatsiya texnologiyalari', 'biznesni boshqarish', 'iqtisodiyot', 'aerokosmik texnologiyalar', 'tarjima nazariyasi va amaliyoti: fransuz tili', 'tarjima nazariyasi va amaliyoti: rus tili', 'ona tili va adabiyoti: turkman tili', 'oziq-ovqat texnologiyasi', 'filologiya va tillarni oʻqitish: ingliz tili', 'infokommunikatsiya injiniringi', 'statistika', 'gidrotexnika inshootlari va nasos stansiyalaridan foydalanish', 'yengil sanoat muhandisligi', 'ona tili va adabiyoti: rus tili', 'soliqlar va soliqqa tortish', 'sotsiologiya', 'metallurgiya muhandisligi', 'elektr muhandisligi', 'veterinariya farmatsevtikasi', 'veterinariya meditsinasi', 'oʻrmonchilik va aholi yashash joylarini koʻkalamzorlashtirish', 'tarjima nazariyasi va amaliyoti: italyan tili', 'agrokimyo va tuproqshunoslik', 'bastakorlik sanʼati', 'texnologik mashinalar va jihozlar', 'turizm va mehmondoʻstlik', 'tarjima nazariyasi va amaliyoti: turk tili', 'zooinjeneriya', 'filologiya va tillarni oʻqitish: rus tili', 'geografiya', 'kartografiya va masofadan zondlash', 'kosmik texnologiyalar', 'arxitektura', 'simsiz aloqa va teleradioeshittirish injiniringi', 'ipakchilik va tutchilik', 'dorivor oʻsimliklarni yetishtirish va qayta ishlash texnologiyasi', 'filologiya va tillarni oʻqitish: fors tili', 'kutubxona-axborot faoliyati', 'marketing', 'muhandislik kommunikatsiyalari qurilish va ekspluatatsiyasi', 'arxeologiya', 'ona tili va adabiyoti: tojik tili', 'psixologiya', 'matbaa va qadoqlash muhandisligi', 'foydali qazilma konlari geologiyasi, qidiruv va razvedkasi'}
Faqat 1-ro'yxatda bor, lekin 2-da yo'qlar: {'rejissyorlik: qoʻgʻirchoq teatr rejissyorligi', 'sport faoliyati: sambo', 'sport faoliyati: basketbol', 'sanʼatshunoslik: sahna va ekran sanʼati dramaturgiyasi', 'dizayn: sanoat dizayni', 'tuproq bonitirovkasi va yer degredatsiyasi', 'sanʼatshunoslik: kino sanʼati tanqidi va tahlili', 'xalqaro huquq va qiyosiy huquqshunoslik', 'sport faoliyati: zamonaviy besh kurash', 'sport faoliyati: yunon-rum kurashi', 'rejissyorlik: maqom teatri rejissyorligi', "cholgʻu ijrochiligi: estrada cholgʻulari (skripka, al't)", 'sport faoliyati: ayollar kurashi', 'sport faoliyati: futbol', 'sport faoliyati: figurali uchish', 'cholgʻu ijrochiligi: xalq cholgʻulari (rubob prima, qashqar va afgʻon rubobi)', 'sport faoliyati: ogʻir atletika', 'rangtasvir: mahobatli rangtasvir', "cholgʻu ijrochiligi: estrada cholgʻulari (violchel', kontrabas)", 'cholgʻu ijrochiligi: estrada cholgʻulari (saksofon)', 'grafika: dastgoh va kitob grafikasi', 'filologiya va tillarni oʻqitish: pushtu tili', 'amaliy sanʼat: badiiy zargarlik', 'sport faoliyati: taekvondo wtf', 'aktyorlik sanʼati: maqom teatri aktyorligi', 'rangtasvir: dastgohli', 'sport faoliyati: kriket', 'sport faoliyati: suzish', 'sanʼatshunoslik: xoreografiya', 'cholgʻu ijrochiligi: estrada cholgʻulari (fleyta, goboy)', "rangtasvir: mul'tfilm va kompyuter multiplikatsiyasi", 'aktyorlik sanʼati: dramatik teatr va kino aktyorligi', 'dizayn: poyabzal va aksessuarlar dizayni', 'sport faoliyati: akademik eshkak eshish', 'sanʼatshunoslik: sanʼat jurnalistikasi', 'sport faoliyati: yengil atletika', 'cholgʻu ijrochiligi: torli cholgʻular (violonchel kontrabas)', 'vokal sanʼati: estrada xonandaligi', 'sport faoliyati: para dzyu-do', 'sport faoliyati: biatlon', 'sport faoliyati: snoubord', 'sanʼatshunoslik: musiqashunoslik', 'sport faoliyati: belbogʻli kurash', 'sport faoliyati: para taekvondo wtf', 'sport faoliyati: badminton', 'sport faoliyati: dzyudo', 'cholgʻu ijrochiligi: fortepiano (organ)', 'kiberhuquq', 'agromuhandislik', 'cholgʻu ijrochiligi: estrada cholgʻulari (zarbli cholgʻular)', 'dizayn: reklama va amaliy grafika', 'xoreografiya (xoreografiya jamoalari rahbari)', 'sport faoliyati: triatlon', 'sanoat muhandisligi va menejmenti', 'sport faoliyati: qo‘l jangi', 'sport faoliyati: velosport', 'amaliy sanʼat: badiiy naqqoshlik', 'dirijyorlik: opera - simfoniya dirijyorligi', 'cholgʻu ijrochiligi: xalq cholgʻulari (chang)', 'xalq ijodiyoti: ashula va raqs', 'xalq ijodiyoti: baxshichilik va dostonchilik', 'sport faoliyati: gimnastika', 'sport faoliyati: bodibilding va fitnes', 'cholgʻu ijrochiligi: xalq cholgʻulari (zarbli cholgʻular)', 'sport faoliyati: chim ustida xokkey', 'sport faoliyati: ot sporti', 'xalq ijodiyoti: anʼanaviy xonandalik', 'sport faoliyati: togʻ changʻisi', 'vokal sanʼati: anʼanaviy xonandalik', 'aktyorlik sanʼati: qoʻgʻirchoq teatr aktyorligi', 'grafika: xattotlik va miniatyura', 'sport faoliyati: fijital basketbol', 'cholgʻu ijrochiligi: estrada cholgʻulari (fortepiano)', 'sport faoliyati: muay tay', 'cholgʻu ijrochiligi: xalq cholgʻulari  (gʻijjak, gʻijjak alt)', 'dizayn: kompyuter grafikasi va badiiy foto', 'xalq ijodiyoti: cholgʻu ijrochiligi', 'cholgʻu ijrochiligi: puflama va zarbli cholgʻular (fleyta, goboy, fagot)', 'xoreografiya (zamonaviy raqs)', 'sport faoliyati: kibersport', 'dizayn: toʻqimachilik va yengil sanoat dizayni', 'dizayn: avtomobilsozlik dizayni', "texnogen san'at: kino, televideniye va radio ovoz rejissorligi", 'qayta tiklanuvchi energiya manbalari', 'tarjima nazariyasi va amaliyoti: ispan tili', 'davlat auditi', 'sport faoliyati: qoʻl toʻpi', 'sport faoliyati: xokkey', 'cholgʻu ijrochiligi: puflama va zarbli cholgʻular (klarnet, saksofon)', 'cholgʻu ijrochiligi: estrada cholgʻulari (trombon)', 'dizayn: kostyum dizayni', 'ona tili va adabiyoti: qirg‘iz tili', 'rangtasvir: teatr-bezak rangtasviri', 'qurilish materiallari, buyumlari va konstruksiyalarini ishlab chiqarish', 'xalq ijodiyoti: folklor va etnografiya', 'amaliy sanʼat: amaliy sanʼat asarlarini taʼmirlash', 'amaliy sanʼat: badiiy kulolchilik', 'dizayn: libos va gazlamalar', 'cholgʻu ijrochiligi: puflama va zarbli cholgʻular (trombon, tuba)', 'cholgʻu ijrochiligi: estrada cholgʻulari (gitara bas)', 'sport faoliyati: voleybol', 'cholgʻu ijrochiligi: xalq cholgʻulari (gʻijjak qobus bas, gʻijjak qobus - kontrabas)', 'sport faoliyati: regbi', 'aktyorlik sanʼati: musiqali teatr aktyorligi', 'sunʼiy intellekt va kiberxavfsizlik', 'sport faoliyati: badiiy gimnastika', "sport faoliyati: o‘zbek jang san'ati", 'dirijyorlik: estrada orkestri dirijyorligi', 'sport faoliyati: tennis', 'sport faoliyati: shaxmat', 'cholgʻu ijrochiligi: torli cholgʻular (skripka, alt)', 'cholgʻu ijrochiligi: anʼanaviy cholgʻular', 'sport faoliyati: kamondan otish', 'cholgʻu ijrochiligi: xalq cholgʻulari (nay-qoʻshnay, bayan-akkordeon)', 'sport faoliyati: karate wkf', 'sport faoliyati: penchak silat', 'cholgʻu ijrochiligi: xalq cholgʻulari (dutor, dutor bas, dutor kontrabas,tanbur, dombira)', 'cholgʻu ijrochiligi: estrada cholgʻulari (gitara)', 'rejissyorlik: dramatik teatr rejissyorligi', 'barqaror transport', 'sport faoliyati: suv polosi', 'rejissyorlik: kino va televideniye  rejissyorligi', 'xalq ijodiyoti: folklor ijrochiligi', 'rejissyorlik: musiqali teatr rejissyorligi', 'cholgʻu ijrochiligi: puflama va zarbli cholgʻular (klarnet, fagot)', 'sanʼatshunoslik: tasviriy va amaliy sanʼat', 'sport faoliyati: sinxron suzish', 'haykaltaroshlik: mahobatli', 'rangtasvir: filmning tasviriy yechimi', 'dizayn: landshaft dizayni', 'sport faoliyati: para yengil atletika', 'cholgʻu ijrochiligi: estrada cholgʻulari (truba)', 'sport faoliyati: para suzish', 'sport faoliyati: stol tennisi', 'sport faoliyati: kik-boks', 'sport faoliyati: mini-futbol', 'cholgʻu ijrochiligi: puflama va zarbli cholgʻular (valtorna, truba)', 'rejissyorlik: estrada va ommaviy tomoshalar rejissyorligi', 'sport faoliyati: qilichbozlik', 'sport faoliyati: para paurlifting', 'sport faoliyati: boks', 'dizayn: milliy kostyum', 'sport faoliyati: turon', 'amaliy sanʼat:  sozgarlik', 'sport faoliyati: erkin kurash', 'ishlab chqarish muhandisligi', 'sport faoliyati: para velosport', 'dirijyorlik: akademik xor dirijyorligi', 'sport faoliyati: o‘q otish va stenddan o‘q otish', 'amaliy sanʼat: meʼmoriy yodgorliklar bezagini taʼmirlash', 'vokal sanʼati: akademik xonandalik', 'neftʼ va neft-gazni qayta ishlash texnologiyasi', 'sport faoliyati: eshkak eshish', "texnogen san'at: musiqiy ovoz rejissorligi", 'dizayn: mediadizayn', 'aktyorlik sanʼati: estrada aktyorligi', 'islom iqtisodiyoti va moliyasi', 'sport faoliyati: sport akrobatikasi', 'sport faoliyati: kurash', 'dizayn: interyer dizayni', 'raqamli huquq', 'sport faoliyati: fijital futbol', 'cholgʻu ijrochiligi: puflama va zarbli cholgʻular (zarbli cholgʻular)', 'sanʼatshunoslik: teatrshunoslik', 'islomiy moliya', 'xorijiy til va adabiyoti: xitoy tili'}
Faqat 2-ro'yxatda bor, lekin 1-da yo'qlar: {'amaliy sanʼat', 'tuproq bonitirovkasi va yer degradatsiyasi', 'sanʼatshunoslik', 'grafika', 'filologiya va tillarni oʻqitish: urdu tili', 'vokal sanʼati', 'xalq ijodiyoti', 'rangtasvir', 'seysmologiya va seysmometriya', 'dirijyorlik', 'aktyorlik sanʼati', 'neft va neft-gazni qayta ishlash texnologiyasi', 'filologiya va tillarni oʻqitish: hind tili', 'xoreografiya', 'filologiya va tillarni oʻqitish: malay tili', 'sport faoliyati', 'mamlakatshunoslik', 'bojxona ishi', 'texnogen sanʼat', 'haykaltaroshlik', 'ona tili va adabiyoti: qirgʻiz tili', 'cholgʻu ijrochiligi', 'texnologik mashinalar va jihozlar: yogʻochga ishlov berish texnologiyasi', 'rejissyorlik', 'dizayn', 'filologiya va tillarni oʻqitish: uygʻur tili'}

In [93]:
# 1. df_abts dagi 'yonalishi' ustunini vaqtinchalik tozalab, 'topilmaganlar' ro'yxatida mavjudligini tekshiramiz
xato_qatorlar_maskasi = df_abts['yonalishi'].astype(str).str.strip().str.lower().isin(set1.difference(set2))

# 2. ~ (tilde) belgisi yordamida ushbu XATO qatorlarni olib tashlab, faqat to'g'rilarini df_abts ga qayta saqlaymiz
df_abts = df_abts[~xato_qatorlar_maskasi]

# Natijani tekshirish
print("Xato qatorlar olib tashlangandan keyingi jami qatorlar soni:", len(df_abts))

Xato qatorlar olib tashlangandan keyingi jami qatorlar soni: 344701

In [94]:
# 1. Ikkala jadvalda ham barcha harflari kichik va probellari tozalangan yordamchi (join_key) ustun yaratamiz
df_abts['join_key'] = df_abts['yonalishi'].astype(str).str.strip().str.lower()
df_yonalishlar['join_key'] = df_yonalishlar['Bakalavriat taʼlim yoʻnalishlari nomi'].astype(str).str.strip().str.lower()

# 2. Shu tozalangan yordamchi ustun bo'yicha LEFT JOIN qilamiz
merged_df = pd.merge(
    df_abts,
    df_yonalishlar,
    how='left',
    on='join_key'  # Birlashtirish shu ustun asosida bo'ladi
)

# 3. Birlashtirish muvaffaqiyatli yakunlangach, jadvaldagi yordamchi 'join_key' ustunini o'chirib tashlaymiz
merged_df = merged_df.drop(columns=['join_key'])

# (Ixtiyoriy) Asl jadvallar ham toza turishi uchun ulardan ham o'chirib qo'yamiz
df_abts = df_abts.drop(columns=['join_key'])
df_yonalishlar = df_yonalishlar.drop(columns=['join_key'])

# Natijani tekshirish uchun dastlabki 5 ta qatorni ko'ramiz
merged_df.head()

,ismi,ID,otm_nomi,yonalishi,shifr_kodi,talim_tili,talim_shakli,toplagan_bali,Yoʻnalish kodi,Bakalavriat taʼlim yoʻnalishlari nomi,1-fan,2-fan
0,URAKBAYEV N. M.,6042695,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,189.0,60540200,Amaliy matematika,Matematika,Fizika
1,NAZEROV I. A.,6045467,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,189.0,60540200,Amaliy matematika,Matematika,Fizika
2,TENGELOV X. I.,6872807,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,189.0,60540200,Amaliy matematika,Matematika,Fizika
3,JANABAYEV S. O.,6259423,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,186.7,60540200,Amaliy matematika,Matematika,Fizika
4,ERDOSHEVA X. T.,6980903,Nukus davlat pedagogika instituti,Amaliy matematika,60540200,O'zbekcha,Kunduzgi,185.7,60540200,Amaliy matematika,Matematika,Fizika

In [95]:
merged_df.shape

(344701, 12)

In [96]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344701 entries, 0 to 344700
Data columns (total 12 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   ismi                                   344701 non-null  str
 1   ID                                     344701 non-null  int64
 2   otm_nomi                               344701 non-null  str
 3   yonalishi                              344701 non-null  str
 4   shifr_kodi                             344701 non-null  int64
 5   talim_tili                             344701 non-null  str
 6   talim_shakli                           344701 non-null  str
 7   toplagan_bali                          344701 non-null  float64
 8   Yoʻnalish kodi                         344701 non-null  int64
 9   Bakalavriat taʼlim yoʻnalishlari nomi  344701 non-null  str
 10  1-fan                                  344701 non-null  str
 11  2-fan                                  344701 non-null  str
dtypes: float64(1), int64(3), str(8)
memory usage: 31.6 MB

In [97]:
merged_df = merged_df[['ismi', 'ID', 'toplagan_bali', '1-fan', '2-fan']]

In [98]:
merged_df.head()

              ismi       ID  toplagan_bali       1-fan   2-fan
0  URAKBAYEV N. M.  6042695          189.0  Matematika  Fizika
1    NAZEROV I. A.  6045467          189.0  Matematika  Fizika
2   TENGELOV X. I.  6872807          189.0  Matematika  Fizika
3  JANABAYEV S. O.  6259423          186.7  Matematika  Fizika
4  ERDOSHEVA X. T.  6980903          185.7  Matematika  Fizika

In [99]:
merged_df.to_csv('../data/processed/real_abts.csv', index=False)